config/routes.rb
Rails.application.routes.draw do
  get "notices/index"
  get "notices/show"
  get "notices/search"
  get "sessions/new"
  devise_for :users

  get "/login", to: "sessions#new"
  resources :users, only: [ :show, :edit, :update ]
  resources :categories, only: [ :index, :new, :create, :edit, :update, :destroy ]
  resources :transactions, only: [ :index, :new, :create, :edit, :update, :destroy ]
  resources :dashboards, only: [ :index ]
  resources :cryptos, only: [:index, :show] do
    collection do
      post :update_prices # Para criar a ação de atualização
    end
  end
  resources :notices, only: [:index, :show, :create] do
    collection do
      get :search
    end
  end
  resources :lots, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/notice.rb
# == Schema Information
#
# Table name: notices
#
#  id          :bigint           not null, primary key
#  code        :string
#  description :string
#  end_date    :date
#  link        :string
#  lots_count  :integer
#  start_date  :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Notice < ApplicationRecord
  has_many :lots
  validates :code, :description, :start_date, :end_date, :lots_count, presence: true
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
    @notices = Notice.all
  end

  def show
    @notice = Notice.includes(:lots).find(params[:id])
  end

  def search
    @results = Lot.where("lot LIKE ?", "%#{params[:query]}%")
  end

  def create
    # Here you can handle the logic to save the notice.
    notice = Notice.new(notice_params)

    if notice.save
      render json: notice, status: :created
    else
      render json: { errors: notice.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def notice_params
    params.require(:notice).permit(:code, :description, :start_date, :end_date, :lots_count)
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/index.html.erb
<% @notices.each do |notice| %>
  <h3><%= link_to notice.description, notice_path(notice) %></h3>
  <p><%= notice.start_date %> - <%= notice.end_date %></p>
  <p>Lotes: <%= notice.lots_count %></p>
<% end %>

app/views/notices/search.html.erb
<h1>Buscar Lotes</h1>
<%= form_tag(search_notices_path, method: :get) do %>
  <%= label_tag :query, "Buscar por Macbook" %>
  <%= text_field_tag :query %>
  <%= submit_tag "Pesquisar" %>
<% end %>

<% if @results.any? %>
  <h3>Resultados:</h3>
  <% @results.each do |lot| %>
    <p><%= lot.notice.description %> - Lote <%= lot.lot %>: <%= lot.min_price %> - <%= lot.status %></p>
  <% end %>
<% else %>
  <p>Nenhum resultado encontrado.</p>
<% end %>

app/views/notices/show.html.erb
<h1><%= @notice.description %></h1>
<p><%= @notice.code %></p>
<p><%= @notice.start_date %> - <%= @notice.end_date %></p>

<h2>Lotes:</h2>
<% @notice.lots.each do |lot| %>
  <p><%= lot.lot_number %>: <%= lot.min_price %> - <%= lot.status %></p>
<% end %>